### PR TITLE
FLOR-42 Added ViewSwitcher & refactoring

### PR DESCRIPTION
**Pull request by joe-campuswien**

### CODE REVIEW

**Comment by joe-campuswien** [comment]
- [x] implement navigation util
- [ ] check whether semi-responsive layout prep should be handled in this PR
- [ ] check if base-view needed

**Comment by joe-campuswien** [comment]
Regarding test setup: javaFx testing library 'testFx' is a huge pain in the ass when trying to use it with jigsaw modules & gradle -> won't add for now

**Comment by alan-mat** [comment]
Can we get some screenshots of what you've accomplished so far? Treat it as a documentation.

**Review by grubengraeber — APPROVED** [review]
Looks awesome already! A good base to continue working on! Thank you

**Comment by joe-campuswien** [comment]
> Can we get some screenshots of what you've accomplished so far? Treat it as a documentation.

https://floridsdorf.atlassian.net/browse/FLOR-42?focusedCommentId=10007

I've added a screenshot to the corresponding issue, as well as a status update for documentation purposes. You might want to start the application to further inspect the progress, as @grubengraeber has done quite a lot of base-setup for all the other views.

**Comment by alan-mat** [comment]
Nice thank you 👍

**Pull request merged**
