### PR TITLE
FLOR-33 - Networking of prototype game logic

### PR DESCRIPTION
**Pull request by s9mert**

### CODE REVIEW

**Comment by alan-mat** [comment]
Wird reingemerged nach Abschluss der Integration mit bestehender Game Logik.

**Comment by alan-mat** [comment]
Networking semi-integrated, currently works as a chat app. Must add (/rewrite) game logic and put it together with the networking and then it's done.

**Review by alan-mat — APPROVED** [review]
@s9mert please provide a review as well. I can't request your approval.

**Comment by s9mert** [comment]
LGTM !

**Pull request merged**
